name: Manual
on: 
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: taketake
        required: true
        description: test

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "{{ inputs.greeting }}"
